module.exports = {
    REQUEST_MESSAGES: "REQUEST_MESSAGES",
    RECEIVE_MESSAGES: "RECEIVE_MESSAGES",
    GET_MESSAGES: "GET_MESSAGES",
    UPDATE_CURRENT_MESSAGE: "UPDATE_CURRENT_MESSAGE",
    ADD_MESSAGE: "ADD_MESSAGE",
}