module.exports = {
    //Chat message events
    REQUEST_MESSAGES_BY_ROOM: "REQUEST_MESSAGES_BY_ROOM",
    RECEIVE_MESSAGES: "RECEIVE_MESSAGES",
    GET_MESSAGES: "GET_MESSAGES",
    UPDATE_CURRENT_MESSAGE: "UPDATE_CURRENT_MESSAGE",
    ADD_MESSAGE: "ADD_MESSAGE",
    //Game list events
    REQUEST_GAMES_BY_STATUS: "REQUEST_GAMES_BY_STATUS",
    RECEIVE_GAMES_BY_STATUS: "RECEIVE_GAMES_BY_STATUS",
    CREATE_GAME: "CREATE_GAME",
    UPDATE_GAME: "UPDATE_GAME",
    DELETE_GAME: "DELETE_GAME"
}